import styled from "@emotion/styled";

export const button = styled.button(() => ({
      backgroundImage: 'linear-gradient(#42A1EC, #0070C9)',
      border: '1px solid #0077CC',
      borderRadius: '4px',
      boxSizing: 'border-box',
      color: '#FFFFFF',
      cursor: 'pointer',
      direction: 'ltr',
      display: 'block',
      fontFamily: 'SF Pro Text,SF Pro Icons,AOS Icons,Helvetica Neue,Helvetica,Arial,sans-serif',
      fontSize: '17px',
      fontWeight: '400',
      letterSpacing: '-.022em',
      lineHeight: '1.47059',
      minWidth: '30px',
      overflow: 'visible',
      padding: '4px 15px',
      textAlign: 'center',
      verticalAlign: 'baseline',
      userSelect: 'none',
      webkitUserSelect: 'none',
      touchAction: 'manipulation',
      whiteSpace: 'nowrap',
}))